### ISSUE TITLE
Cannot reproduce video at "Inviting members to your team" section

### ISSUE THREAD

**Issue by esau-morais** [useflytrap/flytrap-js#1]
### 🐛 The bug

[Inviting members to your team section](https://docs.useflytrap.com/understanding/collaborating-with-team#inviting-members-to-your-team)

![Inviting members to your team section](https://github.com/useflytrap/flytrap-js/assets/55207584/dde80637-9747-4336-abe7-39fb61f91a36)

### 🛠️ To reproduce

https://docs.useflytrap.com/understanding/collaborating-with-team#inviting-members-to-your-team

### 🌈 Expected behaviour

Should get to play video

**Comment by skoshx** [comment]
Hello! Thanks a lot for reporting this, we will fix it ASAP :)
