### ISSUE TITLE
I can't import useflytrap/transform in next-config.js

### ISSUE THREAD

**Issue by miracim** [useflytrap/flytrap-js#2]
### 📚 Is your documentation request related to a problem?

I want to add the useflytrap package to NextJS 13.5, but the error it gives me is 

**next-config.js**
`import { FlytrapTransformPlugin } from 'useflytrap/transform';`

**terminal**
`SyntaxError: Cannot use import statement outside a module`

**Comment by skoshx** [comment]
Hello @turkgenciyim , and thanks for the issue!

The above syntax error means that your next config uses the CJS (CommonJS) Syntax.

Importing as below should fix the issue:

```typescript
const { FlytrapTransformPlugin } = require('useflytrap/transform');
```

Let me know if it fixes things! :)

**Comment by esau-morais** [comment]
or either follow the docs as it instructs to use the `.mjs` file extension and the default export

**Comment by skoshx** [comment]
Closing as the issue is stale. Let me know if you need any more help :)
